# Generated by Django 4.2 on 2023-04-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connections',
            field=models.ManyToManyField(blank=True, to='connectApp.profile'),
        ),
    ]
