# Generated by Django 4.2 on 2023-04-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0005_post_likes_like_comment'),
    ]

    operations = [
    ]
