# Generated by Django 4.2 on 2023-04-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0005_post_likes_like_comment'),
        ('connectApp', '0006_auto_20230424_0201'),
    ]

    operations = [
    ]
