# Generated by Django 4.2 on 2023-04-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0007_comment_timestamp_post_comments_alter_comment_post_and_more'),
        ('connectApp', '0007_merge_20230424_0209'),
    ]

    operations = [
    ]
