# Generated by Django 4.2 on 2023-04-24 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectApp', '0008_merge_20230424_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(default=1, related_name='comment_likes', through='connectApp.CommentLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
