# Generated by Django 4.2 on 2023-04-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0010_alter_comment_likes'),
    ]

    operations = [

    ]
