# Generated by Django 4.2 on 2023-04-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0013_comment_likes_delete_commentlike'),
    ]

    operations = [

    ]
