# Generated by Django 4.2 on 2023-04-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0016_comment_likes_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
