# Generated by Django 4.2 on 2023-05-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0019_alter_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
